[GLOBAL]
pants_version = "2.10.0"
backend_packages = [
  "pants.backend.python",
]

use_deprecated_python_macros = false

[anonymous-telemetry]
enabled = false

[source]
# marker_filenames = ["pyproject.toml"]