python_sources()

pex_binary(
  name="lib1_pex",
  entry_point="src/acme_corp/lib1/lib1_module.py:lib1func"
)

# python_distribution(
#     name="lib1dist",
#     dependencies=[
#         'acme_corp.lib1'
#     ],
#     sdist=True,
#     provides=python_artifact(
#         name="acme_corp.lib1",
#         version="0.0.0",
#     ),
# )

